# My first workflow

name: workflow1
on:
  push:
    branches:
      - 'release/**'
    paths:
      - '**.js'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 for testing
        run: echo "hello from Asyraf"
      - name: step 2
        run: echo "update release"

  
