#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: self-hosted
    steps: 
      - name: step1
        run: |
          echo "hello from Asyraf"
          sleep 5
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 5
          hostname
          touch /tmp/intelmar
          sleep 5
## Name is not important in a step
      - run: uname -a
  
