#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: self-hosted
    env:
      greetings: "hello"
    steps: 
      - name: step1
        run: |
          echo "$greetings! from $name . $name created this file"
          env:
            name: Asyraf
      - name: step2 for testing
        run: |
          cat /etc/os-release
          hostname
          echo "$greetings! from $.name"
          touch /tmp/asyraf_release

          
## Name is not important in a step
      - run: uname -a
  
