#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:
env:
  greetings: "Good Morning"
  name: "Mark"
  lastname: "Mario"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      greetings: "hello"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name . $name created this ${{ vars.APP_NAME }} under repo ${{ GITHUB.REPOSITORY }} and its running on OS ${{ RUNNER.OS }}"
          echo Application name is ${{ vars.APP_NAME }}
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}
          sleep 20
        env:
            name: Asyraf
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 10
          hostname
          echo "$greetings ! from $name"
          touch /tmp/asyraf_release

          
## Name is not important in a step
      - run: uname -a

      ##job2##
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      lastname: "ridzuan"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name $lastname . $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}
          sleep 10
        env:
            name: Asyraf
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 10
          hostname
          echo "$greetings ! from $name"
          touch /tmp/asyraf_release

  test:
      runs-on: ubuntu-latest
      environment: test
      env:
        lastname: "ridzuan"
      steps: 
        - name: step1
          run: |
            echo "$greetings ! from $name $lastname . $name created this file"
            echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}
            sleep 5
           

  
