#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:
env:
  greetings: "Good Morning"
  name: "Mark"
  lastname: "Mario1"

jobs:
  build: 
    runs-on: ubuntu-latest
    ##continue-on-error: true
    environment: dev
    env:
      greetings: "hello"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name . $name created this ${{ vars.APP_NAME }} under repo ${{ GITHUB.REPOSITORY }} and its running on OS ${{ RUNNER.OS }}"
          echo Application name is ${{ vars.APP_NAME }} and password for the same is ${{  secrets.SERVER_PASSWORD }}
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}"
          sleep 5
        env:
            name: Asyraf
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 5
      - name: step3 for error testing
        run: |  
          hostname
          echo "$greetings ! from $name"
          touch /tmp/asyraf_release

      ## Name is not important in a step
      - run: uname -a
   
  test:
      runs-on: ubuntu-latest
      ##continue-on-error: true
      environment: test
      needs: build
      env:
        lastname: "jinggo"
      steps: 
        - name: step1
          run: |
            echo "$greetings ! from $name $lastname . $name created this file"
            echo Application name is ${{ vars.APP_NAME }}
            echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}"
            sleep 5

  stage:
    runs-on: ubuntu-latest
    needs: test
    environment: prod
    env:
      lastname: "ridzuan"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name $lastname . $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}"
          sleep 5
        env:
            name: Asyraf
          
  deploy:
    runs-on: ubuntu-latest
    needs: stage
    environment: prod
    env:
      lastname: "ridzuan"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name $lastname . $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}"
          sleep 5
        env:
            name: Asyraf
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 5
          hostname
          echo "$greetings ! from $name"
          touch /tmp/asyraf_release




           

  
